---
abstract: 'run a system command or spawn a system processes'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  Cwd: '0'
  Data::Dumper: '0'
  File::Spec: '0'
  File::Temp: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4216, CPAN::Meta::Converter version 2.142690'
keywords: []
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sys-Cmd
provides:
  Sys::Cmd:
    file: lib/Sys/Cmd.pm
    version: v0.85.4
  Sys::Cmd::Template:
    file: lib/Sys/Cmd/Template.pm
    version: v0.85.4
requires:
  Carp: '0'
  Exporter::Tidy: '0'
  File::Which: '0'
  File::chdir: '0'
  IO::Handle: '0'
  Log::Any: '0'
  Proc::FastSpawn: '0'
resources:
  bugtracker: https://github.com/mlawren/p5-Sys-Cmd/issues
  homepage: https://github.com/mlawren/p5-Sys-Cmd
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: git://github.com/mlawren/p5-Sys-Cmd.git
version: v0.85.4
