---
abstract: 'run a system command or spawn a system processes'
author:
  - 'Mark Lawrence <mark@rekudos.net>'
build_requires:
  Cwd: '0'
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.09'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sys-Cmd
no_index:
  directory:
    - t
    - inc
  package:
    - Sys::Cmd::Mo
requires:
  Carp: '0'
  Exporter::Tidy: '0'
  File::Which: '0'
  File::chdir: '0'
  IO::Handle: '0'
  Log::Any: '0'
  Proc::FastSpawn: '0'
resources:
  repository: ssh://git@github.com/mlawren/p5-Sys-Cmd.git
version: v0.99.1_1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
